---
deployment:
  tasks:
    - export DEPLOYPATH=/home/l629cgouirbi/public_html/speechpacer
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp -R contactform $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R img $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp -R lib $DEPLOYPATH
